application: chromiumcodereview
version: 4
runtime: python
api_version: 1

default_expiration: 7d  # This is good for images, which never change

# The commented "secure: always" handler can't be enabled for appspot.com
# applications with a custom domain, since GAE doesn't support HTTPS on custom
# domains at the moment.
handlers:

- url: /(robots.txt|favicon.ico)
  static_files: static/\1
  upload: static/(robots.txt|favicon.ico)

- url: /google7db36eb2cc527940.html
  static_files: static/robots.txt
  upload: static/robots.txt

- url: /static/upload.py
  script: main.py
#  secure: always

- url: /static/(script.js|styles.css)
  static_files: static/\1
  upload: static/(script.js|styles.css)
  expiration: 1h  # Shorter expiration, these change often
#  secure: always

- url: /static
  static_dir: static
#  secure: always

- url: .*
  script: main.py
#  secure: always

admin_console:
  pages:
  - name: Appstats
    url: /_ah/stats

inbound_services:
- mail
- xmpp_message
- warmup

builtins:
- appstats: on
- mapreduce: on
- remote_api: on
